### ISSUE TITLE
Python 3.9 support

### ISSUE THREAD

**Issue by dantownsend** [piccolo-orm/piccolo_api#2]
Currently broken by pydantic - waiting for a fix.

```
../../../virtualenv/python3.9-dev/lib/python3.9/site-packages/fastapi/dependencies/utils.py:265: in get_typed_annotation
    annotation = evaluate_forwardref(annotation, globalns, globalns)
../../../virtualenv/python3.9-dev/lib/python3.9/site-packages/pydantic/typing.py:50: in evaluate_forwardref
    return type_._evaluate(globalns, localns)
E   TypeError: _evaluate() missing 1 required positional argument: 'recursive_guard'
```

**Comment by dantownsend** [comment]
Was broken here: https://github.com/python/cpython/commit/653f420b53a3aa87316cef59de8d3f5d9e11deb4#diff-015978a768b517a38abbc0ecdea87f5a

Fix in progress: https://github.com/samuelcolvin/pydantic/pull/1844

**Comment by heliumbrain** [comment]
@dantownsend guessing this can be closed? Ptyhon 3.9 support was added in Pydantic 1.7 and piccolo API seems to work fine with 3.9 now

**Comment by dantownsend** [comment]
@heliumbrain Yes, good point - just need to add the Python 3.9 classifier to setup.py.
